#!/bin/bash
#
# RPi Alarm Clock helper. Sends commands to the alarm server socket.
#
# Copyright (C) 2025  Luke Davidson  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

cmd=$1
supported_commands=("start", "stop")

match=0
for i in "${supported_commands[@]}"; do
    if [ $i = "$cmd" ]; then
        match=1
        break
    fi
done
if [ $match -eq 0 ]; then
    echo "Fatal error. Command $cmd not supported."
    exit 1
fi

echo "$cmd" > /dev/tcp/localhost/9999
