#!/bin/bash

sound_file='/home/luke/git/remote/oncall-monitor/siren.wav'

usage() {
    printf "Usage: %s: [-s seconds] COMMAND\n" $0
    echo "COMMAND   DESCRIPTION"
    echo "start     Start the service." 
    echo "stop      Stop the service." 
    echo "restart   Restart the oncall service. Use [-s seconds] flag for a delayed restart." 
    echo "config    View or set configuration."
    exit 2
}

sflag=
while getopts s: name; do
    case $name in
        a)  sflag=1
            sval="$OPTARG";;
        ?)  usage;;
    esac
done
shift $(($OPTIND - 1))

start() {
    startcheck() {
        systemctl --user start oncall-monitor.service 
	sleep 3
        systemctl --user status oncall-monitor.service > /dev/null
        if [[ $? ]]; then
            echo "Service started successfully"
        else
            echo "Service failed to start. Sounding the alarm."
            trap "echo Exited!; exit;" SIGINT SIGTERM
            while [[ true ]]; do
                aplay -r 480000 "$sound_file" 2> /dev/null
            done
        fi
    }
    if [ ! -z "$sflag" ]; then
        if [ ! -z "$sval" ]; then
            sleep "$sval"
            startcheck
        else
            echo "No value for seconds. Please specify a value for -s"
        fi
    else
        startcheck
    fi
}

stop() {
    question="Yes, I really, really want to stop the monitor and do not need it any longer."
    printf "Stop service? Type the following to confirm service stop: \n%s\n"  "$question"
    read input
    if [ "$input" == "$question" ]; then
        systemctl --user stop oncall-monitor.service && echo "Successfully stopped the service"
    else
        echo "Failed to get confirmation to stop service."
        exit 1
    fi
}

restart() {
    systemctl --user stop oncall-monitor.service
    sleep 3
    start
}

config() {
    setdevice() {
        pactl get-source-volume "$1" > /dev/null
	if [ $? == 0 ]; then
            echo "$1" > "$HOME/.local/share/oncall-monitor/device"
        fi
    } 
    if [ "$2" == "set" ]; then
        case "$3" in
            device)	setdevice "$4";;
            wav)	cp "$4" "$HOME/.local/share/oncall-monitor/siren.wav";;
	esac
    fi
    if [ "$2" == "get" ]; then
        echo "Device: $(cat $HOME/.local/share/oncall-monitor/device)"
    fi
}

case "$1" in
    start)      start;;
    stop)       stop;;
    restart)    restart;;
    config)     config "$@";;
    *)          usage;;
esac
